# Generated by Django 5.2.7 on 2025-10-16 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='banner',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
