# Generated by Django 4.2.27 on 2026-04-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fitness_groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField()),
                ('body', models.TextField()),
                ('score', models.IntegerField(default=0)),
                ('groups', models.ManyToManyField(related_name='members', to='fitness_groups.fitnessgroup')),
            ],
        ),
    ]
