# Generated by Django 4.2.27 on 2026-04-13 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ('groups', '0002_rename_group_fitnessgroup'),
    ('users', '0002_users_group_users_score'),
]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='group',
        ),
        migrations.AddField(
            model_name='users',
            name='groups',
            field=models.ManyToManyField(related_name='members', to='groups.fitnessgroup'),
        ),
    ]
