# Generated by Django 4.2.27 on 2026-04-14 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_users_group_users_groups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='groups',
            new_name='fitness_groups',
        ),
    ]
