# Generated by Django 4.2.27 on 2026-04-15 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_groups_users_fitness_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='fitness_groups',
        ),
        migrations.RemoveField(
            model_name='users',
            name='score',
        ),
    ]
