# Generated by Django 6.0 on 2025-12-24 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wearables', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wearableconnection',
            old_name='access_Token',
            new_name='access_token',
        ),
        migrations.RenameField(
            model_name='wearableconnection',
            old_name='refresh_Token',
            new_name='refresh_token',
        ),
    ]
