# Generated by Django 6.0 on 2025-12-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wearables', '0002_rename_access_token_wearableconnection_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wearableconnection',
            name='oura_user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
