# Generated by Django 6.0 on 2025-12-25 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wearables', '0003_wearableconnection_oura_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wearableconnection',
            old_name='oura_user_id',
            new_name='external_user_id',
        ),
    ]
