# Generated by Django 5.2.7 on 2025-10-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardio',
            name='duration',
            field=models.IntegerField(max_length=75),
        ),
    ]
