# Generated by Django 5.2.7 on 2025-10-21 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_alter_cardio_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardio',
            name='duration',
            field=models.PositiveIntegerField(),
        ),
    ]
