# Generated by Django 5.2.7 on 2025-12-03 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0004_comment_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardio',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
