# Generated by Django 5.2.7 on 2025-12-03 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0005_alter_cardio_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardio',
            name='duration',
        ),
    ]
