# Generated by Django 5.2.7 on 2025-12-03 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0006_remove_cardio_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardio',
            name='duration',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
