# Generated by Django 5.2.7 on 2025-12-03 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0007_cardio_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardio',
            name='duration',
            field=models.FloatField(default=60),
        ),
    ]
