# Generated by Django 6.0 on 2025-12-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0008_alter_cardio_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardio',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
