# Generated by Django 4.2.27 on 2026-02-06 03:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0009_cardio_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardio',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='gym',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
