# Generated by Django 4.2.27 on 2026-04-16 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0010_alter_cardio_date_alter_gym_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardio',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gym',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
