# Generated by Django 4.2.27 on 2026-04-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0011_cardio_score_gym_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardio',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gym',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
