# Generated by Django 4.2.27 on 2026-04-16 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0012_alter_cardio_score_alter_gym_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='exercises',
            field=models.JSONField(default=list),
        ),
    ]
