# Generated by Django 4.2.27 on 2026-05-01 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0015_booze_image_cardio_image_gym_image_sport_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='booze',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cardio',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gym',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sport',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
