# Generated by Django 4.2.27 on 2026-04-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Private Group', max_length=255)),
                ('size', models.IntegerField(default=0)),
            ],
        ),
    ]
