"""
Django settings for myBackend project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)#zswis1j=j!pl$^)mp73llo2wf*e7vij_(egc3mw%m&!0a*k_'

# SECURITY WARNING: don't run with debug turned on in production!
# Set DEBUG based on an environment variable. Default to False in production.
DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True' # Set DJANGO_DEBUG=True in local .env

ALLOWED_HOSTS = [
    ".up.railway.app",
    "fitness-website-backend.up.railway.app",
    "localhost",
    "127.0.0.1"
]
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'posts',
    'users',
    'fitness',
    'profile_page',
    'whitenoise.runserver_nostatic',
    'corsheaders',
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",   # MUST be first
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = 'myBackend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myBackend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database Configuration for Railway
# Replace your existing database section with this:

import dj_database_url
import os

if 'RAILWAY_ENVIRONMENT_NAME' in os.environ:
    # Get the DATABASE_URL from Railway
    database_url = os.environ.get('DATABASE_URL', '')
    
    # Parse it
    DATABASES = {
        "default": dj_database_url.parse(database_url)
    }
    
    # CRITICAL: Force disable SSL after parsing
    DATABASES["default"]["OPTIONS"] = {
        "sslmode": "disable",
        "connect_timeout": 10,
    }
    
    print(f"DATABASE_URL: {database_url[:50]}...")  # Print first 50 chars
    print(f"DJANGO DATABASE CONFIG HOST: {DATABASES['default'].get('HOST', 'Not found')}")
    print(f"DJANGO DATABASE CONFIG NAME: {DATABASES['default'].get('NAME', 'Not found')}")
    print(f"DJANGO SSL MODE: {DATABASES['default']['OPTIONS']['sslmode']}")
else:
    # Local development
    DATABASES = {
        'default': dj_database_url.config(
            default='sqlite:///db.sqlite3',
        )
    }
    print("Using local database configuration")
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = BASE_DIR / 'staticfiles' # ADD THIS LINE FOR PRODUCTION

STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

MEDIA_URL = 'media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Session configuration for cross-origin requests
SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'  # Works with same-origin requests (via proxy)
SESSION_COOKIE_NAME = 'sessionid'
SESSION_COOKIE_AGE = 1209600  # 2 weeks
SESSION_COOKIE_DOMAIN = None  # Don't restrict domain for localhost

# CORS settings - Allow cookies to be sent
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
    'https://fitness-website-gilt.vercel.app',
    'https://fitness-website-git-main-rhettselbys-projects.vercel.app',
    'https://fitness-website-n5cwg5gb8-rhettselbys-projects.vercel.app',
]
   

# Trusted origins for CSRF
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
    'https://fitness-website-backend.up.railway.app', 
    "https://fitness-website-gilt.vercel.app",
    "https://fitness-website-git-main-rhettselbys-projects.vercel.app",
    "https://fitness-website-n5cwg5gb8-rhettselbys-projects.vercel.app",
]


CORS_ALLOWED_ORIGIN_REGEXES = [
    "^https://fitness-website.*\.vercel\.app$",
]
SESSION_COOKIE_SAMESITE = "None"
SESSION_COOKIE_SECURE = True

CSRF_COOKIE_SAMESITE = "None"
CSRF_COOKIE_SECURE = True