# Generated by Django 4.2.27 on 2026-04-14 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='FitnessGroup',
        ),
    ]
 