# Generated by Django 4.2.27 on 2026-04-15 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0002_rename_group_fitnessgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitnessgroup',
            name='size',
        ),
        migrations.AddField(
            model_name='fitnessgroup',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='fitness_group', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fitnessgroup',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owned_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
