# Generated by Django 4.2.27 on 2026-04-16 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_remove_fitnessgroup_size_fitnessgroup_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessgroup',
            name='motto',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
